### ISSUE TITLE
entity sensor.electrolux_fridge_wifi_signal_strength (<class 'custom_components.electrolux_status.sensor.ElectroluxStatusSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('signal_strength')

### ISSUE THREAD

**Issue by cloudbr34k84** [mauro-midolo/homeassistant_electrolux_status#62]
entity sensor.electrolux_fridge_wifi_signal_strength (<class 'custom_components.electrolux_status.sensor.ElectroluxStatusSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('signal_strength') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

Apparently these issues are related to where the data is coming from. I have numerous other HACS integrations where this is happening.

**Comment by kovacsla** [comment]
Entity sensor.electrolux_washing_machine_niu_linkqualityindicator (<class 'custom_components.electrolux_status.sensor.ElectroluxStatusSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('signal_strength') it is using; expected one of ['dB', 'dBm']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by allistermaguire** [comment]
SensorDeviceClass.SIGNAL_STRENGTH expects values of dB, dBm. Electrolux is reporting a WiFi Signal Indicator which isn't db or dBm. As far as I can tell it is a scale of 1 to 5 with 5 being Excellent.

The fix is to remove the device_class line (237) from `api.py`
`                device_class=SensorDeviceClass.SIGNAL_STRENGTH,`
