### ISSUE TITLE
Login not working again after core update. 

### ISSUE THREAD

**Issue by wgumaa** [mauro-midolo/homeassistant_electrolux_status#96]
Yesterday there was a core update to 2023.5.3. 

My Electrolux washing machine entities became unavailable. I reloaded the integration several times and it failed. I removed it and tried to install and now keeps giving me an error for the log in saying either username or password is wrong.

**Comment by 35aportal** [comment]
I have the same issue. Detailed log is as follows...

Logger: custom_components.electrolux_status
Source: custom_components/electrolux_status/__init__.py:93
Integration: Electrolux Care Integration ([documentation](https://github.com/mauro-midolo/homeassistant_electrolux_status), [issues](https://github.com/mauro-midolo/homeassistant_electrolux_status/issues))
First occurred: 08:14:39 (170 occurrences)
Last logged: 09:39:10

Invalid API response: Unauthorized (401)
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/__init__.py", line 93, in _async_update_data
    connection_state = await self.hass.async_add_executor_job(self.api.getApplianceConnectionState, appliance)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 1096, in getApplianceConnectionState
    _json = self._requestApi(
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 980, in _requestApi
    raise ResponseError(errcode, message) from None
pyelectroluxconnect.Session.ResponseError: Invalid API response: Unauthorized (401)

**Comment by philr40** [comment]
I have the same issues too, the integration was working fine until very recently. I tried reinstalling the integration but it failed saying that the username or password is incorrect, so I verified my credentials by logging off and back into the AEG Kitchen app, which was successful so fairly certain my credentials are ok. I've also tried firing up VM backup from about a month ago (from before the problem occurred) to see whether the problem was caused by the recent updates but get the same issues on that version too.

I get the following log message is created when attempting to reload the integration

Logger: pyelectroluxconnect.Session
Source: /usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py:211
First occurred: 11:32:06 (3 occurrences)
Last logged: 13:15:54

Exception in _getAppliancesList: Invalid API response: Unauthorized (401)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 186, in _getAppliancesList
    _json = self._requestApi(urls.getAppliances(self._username))
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 978, in _requestApi
    raise ResponseError(errcode, message) from None
pyelectroluxconnect.Session.ResponseError: Invalid API response: Unauthorized (401)

**Comment by DragonQ** [comment]
Same issue here. HA GUI says `Failed to set up: None`

**Comment by CGU1969** [comment]
Same issue here. Logger details:
  Logger: custom_components.electrolux_status
  Source: custom_components/electrolux_status/__init__.py:51
  Integration: Electrolux Care Integration ([documentation](https://github.com/mauro-midolo/homeassistant_electrolux_status), [issues](https://github.com/mauro-midolo/homeassistant_electrolux_status/issues))
  First occurred: 18:13:11 (2 occurrences)
  Last logged: 18:14:07

  
  Could not log in to ElectroluxStatus, Invalid API response: Unauthorized (401)

**Comment by kovacsla** [comment]
Thanks a lot. It is works.

**Comment by CGU1969** [comment]
How can I update the pyelectroluxconnect to fix login, if I have  HA docker instatallation?

**Comment by kovacsla** [comment]
"Home Assistant Studio Code Server => Electrolux Status => manifest.json" 
change the 14. row 
"pyelectroluxconnect==0.3.16"

![image](https://github.com/mauro-midolo/homeassistant_electrolux_status/assets/117943937/2d72c351-bbe4-4007-b84d-851d423bed91)

**Comment by CGU1969** [comment]
Thanks!!! Now It's working!!!

**Comment by mauro-midolo** [comment]
The new versione v2.8.0 reselve the problem.

**Comment by wgumaa** [comment]
Thank you!

**Comment by 35aportal** [comment]
Thanks for the quick fix.

**Comment by philr40** [comment]
Thank you so much for fixing the problem it's all working perfectly again. Very impressed how quickly you managed to resolve it.
